// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteNetworkMerakiAuthUserParams creates a new DeleteNetworkMerakiAuthUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteNetworkMerakiAuthUserParams() *DeleteNetworkMerakiAuthUserParams {
	return &DeleteNetworkMerakiAuthUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteNetworkMerakiAuthUserParamsWithTimeout creates a new DeleteNetworkMerakiAuthUserParams object
// with the ability to set a timeout on a request.
func NewDeleteNetworkMerakiAuthUserParamsWithTimeout(timeout time.Duration) *DeleteNetworkMerakiAuthUserParams {
	return &DeleteNetworkMerakiAuthUserParams{
		timeout: timeout,
	}
}

// NewDeleteNetworkMerakiAuthUserParamsWithContext creates a new DeleteNetworkMerakiAuthUserParams object
// with the ability to set a context for a request.
func NewDeleteNetworkMerakiAuthUserParamsWithContext(ctx context.Context) *DeleteNetworkMerakiAuthUserParams {
	return &DeleteNetworkMerakiAuthUserParams{
		Context: ctx,
	}
}

// NewDeleteNetworkMerakiAuthUserParamsWithHTTPClient creates a new DeleteNetworkMerakiAuthUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteNetworkMerakiAuthUserParamsWithHTTPClient(client *http.Client) *DeleteNetworkMerakiAuthUserParams {
	return &DeleteNetworkMerakiAuthUserParams{
		HTTPClient: client,
	}
}

/* DeleteNetworkMerakiAuthUserParams contains all the parameters to send to the API endpoint
   for the delete network meraki auth user operation.

   Typically these are written to a http.Request.
*/
type DeleteNetworkMerakiAuthUserParams struct {

	// MerakiAuthUserID.
	MerakiAuthUserID string

	// NetworkID.
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete network meraki auth user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteNetworkMerakiAuthUserParams) WithDefaults() *DeleteNetworkMerakiAuthUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete network meraki auth user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteNetworkMerakiAuthUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete network meraki auth user params
func (o *DeleteNetworkMerakiAuthUserParams) WithTimeout(timeout time.Duration) *DeleteNetworkMerakiAuthUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete network meraki auth user params
func (o *DeleteNetworkMerakiAuthUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete network meraki auth user params
func (o *DeleteNetworkMerakiAuthUserParams) WithContext(ctx context.Context) *DeleteNetworkMerakiAuthUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete network meraki auth user params
func (o *DeleteNetworkMerakiAuthUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete network meraki auth user params
func (o *DeleteNetworkMerakiAuthUserParams) WithHTTPClient(client *http.Client) *DeleteNetworkMerakiAuthUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete network meraki auth user params
func (o *DeleteNetworkMerakiAuthUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMerakiAuthUserID adds the merakiAuthUserID to the delete network meraki auth user params
func (o *DeleteNetworkMerakiAuthUserParams) WithMerakiAuthUserID(merakiAuthUserID string) *DeleteNetworkMerakiAuthUserParams {
	o.SetMerakiAuthUserID(merakiAuthUserID)
	return o
}

// SetMerakiAuthUserID adds the merakiAuthUserId to the delete network meraki auth user params
func (o *DeleteNetworkMerakiAuthUserParams) SetMerakiAuthUserID(merakiAuthUserID string) {
	o.MerakiAuthUserID = merakiAuthUserID
}

// WithNetworkID adds the networkID to the delete network meraki auth user params
func (o *DeleteNetworkMerakiAuthUserParams) WithNetworkID(networkID string) *DeleteNetworkMerakiAuthUserParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the delete network meraki auth user params
func (o *DeleteNetworkMerakiAuthUserParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteNetworkMerakiAuthUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param merakiAuthUserId
	if err := r.SetPathParam("merakiAuthUserId", o.MerakiAuthUserID); err != nil {
		return err
	}

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
