// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteNetworkMerakiAuthUserReader is a Reader for the DeleteNetworkMerakiAuthUser structure.
type DeleteNetworkMerakiAuthUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNetworkMerakiAuthUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteNetworkMerakiAuthUserNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteNetworkMerakiAuthUserNoContent creates a DeleteNetworkMerakiAuthUserNoContent with default headers values
func NewDeleteNetworkMerakiAuthUserNoContent() *DeleteNetworkMerakiAuthUserNoContent {
	return &DeleteNetworkMerakiAuthUserNoContent{}
}

/* DeleteNetworkMerakiAuthUserNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type DeleteNetworkMerakiAuthUserNoContent struct {
}

func (o *DeleteNetworkMerakiAuthUserNoContent) Error() string {
	return fmt.Sprintf("[DELETE /networks/{networkId}/merakiAuthUsers/{merakiAuthUserId}][%d] deleteNetworkMerakiAuthUserNoContent ", 204)
}

func (o *DeleteNetworkMerakiAuthUserNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
