// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNetworkSnmpParams creates a new GetNetworkSnmpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNetworkSnmpParams() *GetNetworkSnmpParams {
	return &GetNetworkSnmpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNetworkSnmpParamsWithTimeout creates a new GetNetworkSnmpParams object
// with the ability to set a timeout on a request.
func NewGetNetworkSnmpParamsWithTimeout(timeout time.Duration) *GetNetworkSnmpParams {
	return &GetNetworkSnmpParams{
		timeout: timeout,
	}
}

// NewGetNetworkSnmpParamsWithContext creates a new GetNetworkSnmpParams object
// with the ability to set a context for a request.
func NewGetNetworkSnmpParamsWithContext(ctx context.Context) *GetNetworkSnmpParams {
	return &GetNetworkSnmpParams{
		Context: ctx,
	}
}

// NewGetNetworkSnmpParamsWithHTTPClient creates a new GetNetworkSnmpParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNetworkSnmpParamsWithHTTPClient(client *http.Client) *GetNetworkSnmpParams {
	return &GetNetworkSnmpParams{
		HTTPClient: client,
	}
}

/* GetNetworkSnmpParams contains all the parameters to send to the API endpoint
   for the get network snmp operation.

   Typically these are written to a http.Request.
*/
type GetNetworkSnmpParams struct {

	// NetworkID.
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get network snmp params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkSnmpParams) WithDefaults() *GetNetworkSnmpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get network snmp params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkSnmpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get network snmp params
func (o *GetNetworkSnmpParams) WithTimeout(timeout time.Duration) *GetNetworkSnmpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get network snmp params
func (o *GetNetworkSnmpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get network snmp params
func (o *GetNetworkSnmpParams) WithContext(ctx context.Context) *GetNetworkSnmpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get network snmp params
func (o *GetNetworkSnmpParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get network snmp params
func (o *GetNetworkSnmpParams) WithHTTPClient(client *http.Client) *GetNetworkSnmpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get network snmp params
func (o *GetNetworkSnmpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the get network snmp params
func (o *GetNetworkSnmpParams) WithNetworkID(networkID string) *GetNetworkSnmpParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the get network snmp params
func (o *GetNetworkSnmpParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNetworkSnmpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
