// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateOrganizationConfigTemplateParams creates a new CreateOrganizationConfigTemplateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateOrganizationConfigTemplateParams() *CreateOrganizationConfigTemplateParams {
	return &CreateOrganizationConfigTemplateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateOrganizationConfigTemplateParamsWithTimeout creates a new CreateOrganizationConfigTemplateParams object
// with the ability to set a timeout on a request.
func NewCreateOrganizationConfigTemplateParamsWithTimeout(timeout time.Duration) *CreateOrganizationConfigTemplateParams {
	return &CreateOrganizationConfigTemplateParams{
		timeout: timeout,
	}
}

// NewCreateOrganizationConfigTemplateParamsWithContext creates a new CreateOrganizationConfigTemplateParams object
// with the ability to set a context for a request.
func NewCreateOrganizationConfigTemplateParamsWithContext(ctx context.Context) *CreateOrganizationConfigTemplateParams {
	return &CreateOrganizationConfigTemplateParams{
		Context: ctx,
	}
}

// NewCreateOrganizationConfigTemplateParamsWithHTTPClient creates a new CreateOrganizationConfigTemplateParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateOrganizationConfigTemplateParamsWithHTTPClient(client *http.Client) *CreateOrganizationConfigTemplateParams {
	return &CreateOrganizationConfigTemplateParams{
		HTTPClient: client,
	}
}

/* CreateOrganizationConfigTemplateParams contains all the parameters to send to the API endpoint
   for the create organization config template operation.

   Typically these are written to a http.Request.
*/
type CreateOrganizationConfigTemplateParams struct {

	// CreateOrganizationConfigTemplate.
	CreateOrganizationConfigTemplate CreateOrganizationConfigTemplateBody

	// OrganizationID.
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create organization config template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateOrganizationConfigTemplateParams) WithDefaults() *CreateOrganizationConfigTemplateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create organization config template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateOrganizationConfigTemplateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create organization config template params
func (o *CreateOrganizationConfigTemplateParams) WithTimeout(timeout time.Duration) *CreateOrganizationConfigTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create organization config template params
func (o *CreateOrganizationConfigTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create organization config template params
func (o *CreateOrganizationConfigTemplateParams) WithContext(ctx context.Context) *CreateOrganizationConfigTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create organization config template params
func (o *CreateOrganizationConfigTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create organization config template params
func (o *CreateOrganizationConfigTemplateParams) WithHTTPClient(client *http.Client) *CreateOrganizationConfigTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create organization config template params
func (o *CreateOrganizationConfigTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateOrganizationConfigTemplate adds the createOrganizationConfigTemplate to the create organization config template params
func (o *CreateOrganizationConfigTemplateParams) WithCreateOrganizationConfigTemplate(createOrganizationConfigTemplate CreateOrganizationConfigTemplateBody) *CreateOrganizationConfigTemplateParams {
	o.SetCreateOrganizationConfigTemplate(createOrganizationConfigTemplate)
	return o
}

// SetCreateOrganizationConfigTemplate adds the createOrganizationConfigTemplate to the create organization config template params
func (o *CreateOrganizationConfigTemplateParams) SetCreateOrganizationConfigTemplate(createOrganizationConfigTemplate CreateOrganizationConfigTemplateBody) {
	o.CreateOrganizationConfigTemplate = createOrganizationConfigTemplate
}

// WithOrganizationID adds the organizationID to the create organization config template params
func (o *CreateOrganizationConfigTemplateParams) WithOrganizationID(organizationID string) *CreateOrganizationConfigTemplateParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the create organization config template params
func (o *CreateOrganizationConfigTemplateParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateOrganizationConfigTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.CreateOrganizationConfigTemplate); err != nil {
		return err
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
