// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetOrganizationSummaryTopClientsManufacturersByUsageReader is a Reader for the GetOrganizationSummaryTopClientsManufacturersByUsage structure.
type GetOrganizationSummaryTopClientsManufacturersByUsageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationSummaryTopClientsManufacturersByUsageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationSummaryTopClientsManufacturersByUsageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrganizationSummaryTopClientsManufacturersByUsageOK creates a GetOrganizationSummaryTopClientsManufacturersByUsageOK with default headers values
func NewGetOrganizationSummaryTopClientsManufacturersByUsageOK() *GetOrganizationSummaryTopClientsManufacturersByUsageOK {
	return &GetOrganizationSummaryTopClientsManufacturersByUsageOK{}
}

/* GetOrganizationSummaryTopClientsManufacturersByUsageOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetOrganizationSummaryTopClientsManufacturersByUsageOK struct {
	Payload []interface{}
}

func (o *GetOrganizationSummaryTopClientsManufacturersByUsageOK) Error() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/summary/top/clients/manufacturers/byUsage][%d] getOrganizationSummaryTopClientsManufacturersByUsageOK  %+v", 200, o.Payload)
}
func (o *GetOrganizationSummaryTopClientsManufacturersByUsageOK) GetPayload() []interface{} {
	return o.Payload
}

func (o *GetOrganizationSummaryTopClientsManufacturersByUsageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
