// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReleaseFromOrganizationInventoryReader is a Reader for the ReleaseFromOrganizationInventory structure.
type ReleaseFromOrganizationInventoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReleaseFromOrganizationInventoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReleaseFromOrganizationInventoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewReleaseFromOrganizationInventoryOK creates a ReleaseFromOrganizationInventoryOK with default headers values
func NewReleaseFromOrganizationInventoryOK() *ReleaseFromOrganizationInventoryOK {
	return &ReleaseFromOrganizationInventoryOK{}
}

/* ReleaseFromOrganizationInventoryOK describes a response with status code 200, with default header values.

Successful operation
*/
type ReleaseFromOrganizationInventoryOK struct {
	Payload interface{}
}

func (o *ReleaseFromOrganizationInventoryOK) Error() string {
	return fmt.Sprintf("[POST /organizations/{organizationId}/inventory/release][%d] releaseFromOrganizationInventoryOK  %+v", 200, o.Payload)
}
func (o *ReleaseFromOrganizationInventoryOK) GetPayload() interface{} {
	return o.Payload
}

func (o *ReleaseFromOrganizationInventoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ReleaseFromOrganizationInventoryBody release from organization inventory body
// Example: {}
swagger:model ReleaseFromOrganizationInventoryBody
*/
type ReleaseFromOrganizationInventoryBody struct {

	// Serials of the devices that should be released
	Serials []string `json:"serials"`
}

// Validate validates this release from organization inventory body
func (o *ReleaseFromOrganizationInventoryBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this release from organization inventory body based on context it is used
func (o *ReleaseFromOrganizationInventoryBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ReleaseFromOrganizationInventoryBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ReleaseFromOrganizationInventoryBody) UnmarshalBinary(b []byte) error {
	var res ReleaseFromOrganizationInventoryBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
