// Code generated by go-swagger; DO NOT EDIT.

package appliance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNetworkApplianceFirewallPortForwardingRulesParams creates a new GetNetworkApplianceFirewallPortForwardingRulesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNetworkApplianceFirewallPortForwardingRulesParams() *GetNetworkApplianceFirewallPortForwardingRulesParams {
	return &GetNetworkApplianceFirewallPortForwardingRulesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNetworkApplianceFirewallPortForwardingRulesParamsWithTimeout creates a new GetNetworkApplianceFirewallPortForwardingRulesParams object
// with the ability to set a timeout on a request.
func NewGetNetworkApplianceFirewallPortForwardingRulesParamsWithTimeout(timeout time.Duration) *GetNetworkApplianceFirewallPortForwardingRulesParams {
	return &GetNetworkApplianceFirewallPortForwardingRulesParams{
		timeout: timeout,
	}
}

// NewGetNetworkApplianceFirewallPortForwardingRulesParamsWithContext creates a new GetNetworkApplianceFirewallPortForwardingRulesParams object
// with the ability to set a context for a request.
func NewGetNetworkApplianceFirewallPortForwardingRulesParamsWithContext(ctx context.Context) *GetNetworkApplianceFirewallPortForwardingRulesParams {
	return &GetNetworkApplianceFirewallPortForwardingRulesParams{
		Context: ctx,
	}
}

// NewGetNetworkApplianceFirewallPortForwardingRulesParamsWithHTTPClient creates a new GetNetworkApplianceFirewallPortForwardingRulesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNetworkApplianceFirewallPortForwardingRulesParamsWithHTTPClient(client *http.Client) *GetNetworkApplianceFirewallPortForwardingRulesParams {
	return &GetNetworkApplianceFirewallPortForwardingRulesParams{
		HTTPClient: client,
	}
}

/* GetNetworkApplianceFirewallPortForwardingRulesParams contains all the parameters to send to the API endpoint
   for the get network appliance firewall port forwarding rules operation.

   Typically these are written to a http.Request.
*/
type GetNetworkApplianceFirewallPortForwardingRulesParams struct {

	// NetworkID.
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get network appliance firewall port forwarding rules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkApplianceFirewallPortForwardingRulesParams) WithDefaults() *GetNetworkApplianceFirewallPortForwardingRulesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get network appliance firewall port forwarding rules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkApplianceFirewallPortForwardingRulesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get network appliance firewall port forwarding rules params
func (o *GetNetworkApplianceFirewallPortForwardingRulesParams) WithTimeout(timeout time.Duration) *GetNetworkApplianceFirewallPortForwardingRulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get network appliance firewall port forwarding rules params
func (o *GetNetworkApplianceFirewallPortForwardingRulesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get network appliance firewall port forwarding rules params
func (o *GetNetworkApplianceFirewallPortForwardingRulesParams) WithContext(ctx context.Context) *GetNetworkApplianceFirewallPortForwardingRulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get network appliance firewall port forwarding rules params
func (o *GetNetworkApplianceFirewallPortForwardingRulesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get network appliance firewall port forwarding rules params
func (o *GetNetworkApplianceFirewallPortForwardingRulesParams) WithHTTPClient(client *http.Client) *GetNetworkApplianceFirewallPortForwardingRulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get network appliance firewall port forwarding rules params
func (o *GetNetworkApplianceFirewallPortForwardingRulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the get network appliance firewall port forwarding rules params
func (o *GetNetworkApplianceFirewallPortForwardingRulesParams) WithNetworkID(networkID string) *GetNetworkApplianceFirewallPortForwardingRulesParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the get network appliance firewall port forwarding rules params
func (o *GetNetworkApplianceFirewallPortForwardingRulesParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNetworkApplianceFirewallPortForwardingRulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
