// Code generated by go-swagger; DO NOT EDIT.

package appliance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetOrganizationApplianceVpnVpnFirewallRulesReader is a Reader for the GetOrganizationApplianceVpnVpnFirewallRules structure.
type GetOrganizationApplianceVpnVpnFirewallRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationApplianceVpnVpnFirewallRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationApplianceVpnVpnFirewallRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrganizationApplianceVpnVpnFirewallRulesOK creates a GetOrganizationApplianceVpnVpnFirewallRulesOK with default headers values
func NewGetOrganizationApplianceVpnVpnFirewallRulesOK() *GetOrganizationApplianceVpnVpnFirewallRulesOK {
	return &GetOrganizationApplianceVpnVpnFirewallRulesOK{}
}

/* GetOrganizationApplianceVpnVpnFirewallRulesOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetOrganizationApplianceVpnVpnFirewallRulesOK struct {
	Payload interface{}
}

func (o *GetOrganizationApplianceVpnVpnFirewallRulesOK) Error() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/appliance/vpn/vpnFirewallRules][%d] getOrganizationApplianceVpnVpnFirewallRulesOK  %+v", 200, o.Payload)
}
func (o *GetOrganizationApplianceVpnVpnFirewallRulesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetOrganizationApplianceVpnVpnFirewallRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
