// Code generated by go-swagger; DO NOT EDIT.

package appliance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSwapNetworkApplianceWarmSpareParams creates a new SwapNetworkApplianceWarmSpareParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSwapNetworkApplianceWarmSpareParams() *SwapNetworkApplianceWarmSpareParams {
	return &SwapNetworkApplianceWarmSpareParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSwapNetworkApplianceWarmSpareParamsWithTimeout creates a new SwapNetworkApplianceWarmSpareParams object
// with the ability to set a timeout on a request.
func NewSwapNetworkApplianceWarmSpareParamsWithTimeout(timeout time.Duration) *SwapNetworkApplianceWarmSpareParams {
	return &SwapNetworkApplianceWarmSpareParams{
		timeout: timeout,
	}
}

// NewSwapNetworkApplianceWarmSpareParamsWithContext creates a new SwapNetworkApplianceWarmSpareParams object
// with the ability to set a context for a request.
func NewSwapNetworkApplianceWarmSpareParamsWithContext(ctx context.Context) *SwapNetworkApplianceWarmSpareParams {
	return &SwapNetworkApplianceWarmSpareParams{
		Context: ctx,
	}
}

// NewSwapNetworkApplianceWarmSpareParamsWithHTTPClient creates a new SwapNetworkApplianceWarmSpareParams object
// with the ability to set a custom HTTPClient for a request.
func NewSwapNetworkApplianceWarmSpareParamsWithHTTPClient(client *http.Client) *SwapNetworkApplianceWarmSpareParams {
	return &SwapNetworkApplianceWarmSpareParams{
		HTTPClient: client,
	}
}

/* SwapNetworkApplianceWarmSpareParams contains all the parameters to send to the API endpoint
   for the swap network appliance warm spare operation.

   Typically these are written to a http.Request.
*/
type SwapNetworkApplianceWarmSpareParams struct {

	// NetworkID.
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the swap network appliance warm spare params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SwapNetworkApplianceWarmSpareParams) WithDefaults() *SwapNetworkApplianceWarmSpareParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the swap network appliance warm spare params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SwapNetworkApplianceWarmSpareParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the swap network appliance warm spare params
func (o *SwapNetworkApplianceWarmSpareParams) WithTimeout(timeout time.Duration) *SwapNetworkApplianceWarmSpareParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the swap network appliance warm spare params
func (o *SwapNetworkApplianceWarmSpareParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the swap network appliance warm spare params
func (o *SwapNetworkApplianceWarmSpareParams) WithContext(ctx context.Context) *SwapNetworkApplianceWarmSpareParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the swap network appliance warm spare params
func (o *SwapNetworkApplianceWarmSpareParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the swap network appliance warm spare params
func (o *SwapNetworkApplianceWarmSpareParams) WithHTTPClient(client *http.Client) *SwapNetworkApplianceWarmSpareParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the swap network appliance warm spare params
func (o *SwapNetworkApplianceWarmSpareParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the swap network appliance warm spare params
func (o *SwapNetworkApplianceWarmSpareParams) WithNetworkID(networkID string) *SwapNetworkApplianceWarmSpareParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the swap network appliance warm spare params
func (o *SwapNetworkApplianceWarmSpareParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *SwapNetworkApplianceWarmSpareParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
