// Code generated by go-swagger; DO NOT EDIT.

package appliance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateNetworkApplianceFirewallL7FirewallRulesParams creates a new UpdateNetworkApplianceFirewallL7FirewallRulesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateNetworkApplianceFirewallL7FirewallRulesParams() *UpdateNetworkApplianceFirewallL7FirewallRulesParams {
	return &UpdateNetworkApplianceFirewallL7FirewallRulesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateNetworkApplianceFirewallL7FirewallRulesParamsWithTimeout creates a new UpdateNetworkApplianceFirewallL7FirewallRulesParams object
// with the ability to set a timeout on a request.
func NewUpdateNetworkApplianceFirewallL7FirewallRulesParamsWithTimeout(timeout time.Duration) *UpdateNetworkApplianceFirewallL7FirewallRulesParams {
	return &UpdateNetworkApplianceFirewallL7FirewallRulesParams{
		timeout: timeout,
	}
}

// NewUpdateNetworkApplianceFirewallL7FirewallRulesParamsWithContext creates a new UpdateNetworkApplianceFirewallL7FirewallRulesParams object
// with the ability to set a context for a request.
func NewUpdateNetworkApplianceFirewallL7FirewallRulesParamsWithContext(ctx context.Context) *UpdateNetworkApplianceFirewallL7FirewallRulesParams {
	return &UpdateNetworkApplianceFirewallL7FirewallRulesParams{
		Context: ctx,
	}
}

// NewUpdateNetworkApplianceFirewallL7FirewallRulesParamsWithHTTPClient creates a new UpdateNetworkApplianceFirewallL7FirewallRulesParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateNetworkApplianceFirewallL7FirewallRulesParamsWithHTTPClient(client *http.Client) *UpdateNetworkApplianceFirewallL7FirewallRulesParams {
	return &UpdateNetworkApplianceFirewallL7FirewallRulesParams{
		HTTPClient: client,
	}
}

/* UpdateNetworkApplianceFirewallL7FirewallRulesParams contains all the parameters to send to the API endpoint
   for the update network appliance firewall l7 firewall rules operation.

   Typically these are written to a http.Request.
*/
type UpdateNetworkApplianceFirewallL7FirewallRulesParams struct {

	// NetworkID.
	NetworkID string

	// UpdateNetworkApplianceFirewallL7FirewallRules.
	UpdateNetworkApplianceFirewallL7FirewallRules UpdateNetworkApplianceFirewallL7FirewallRulesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update network appliance firewall l7 firewall rules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateNetworkApplianceFirewallL7FirewallRulesParams) WithDefaults() *UpdateNetworkApplianceFirewallL7FirewallRulesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update network appliance firewall l7 firewall rules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateNetworkApplianceFirewallL7FirewallRulesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update network appliance firewall l7 firewall rules params
func (o *UpdateNetworkApplianceFirewallL7FirewallRulesParams) WithTimeout(timeout time.Duration) *UpdateNetworkApplianceFirewallL7FirewallRulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update network appliance firewall l7 firewall rules params
func (o *UpdateNetworkApplianceFirewallL7FirewallRulesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update network appliance firewall l7 firewall rules params
func (o *UpdateNetworkApplianceFirewallL7FirewallRulesParams) WithContext(ctx context.Context) *UpdateNetworkApplianceFirewallL7FirewallRulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update network appliance firewall l7 firewall rules params
func (o *UpdateNetworkApplianceFirewallL7FirewallRulesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update network appliance firewall l7 firewall rules params
func (o *UpdateNetworkApplianceFirewallL7FirewallRulesParams) WithHTTPClient(client *http.Client) *UpdateNetworkApplianceFirewallL7FirewallRulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update network appliance firewall l7 firewall rules params
func (o *UpdateNetworkApplianceFirewallL7FirewallRulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the update network appliance firewall l7 firewall rules params
func (o *UpdateNetworkApplianceFirewallL7FirewallRulesParams) WithNetworkID(networkID string) *UpdateNetworkApplianceFirewallL7FirewallRulesParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the update network appliance firewall l7 firewall rules params
func (o *UpdateNetworkApplianceFirewallL7FirewallRulesParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WithUpdateNetworkApplianceFirewallL7FirewallRules adds the updateNetworkApplianceFirewallL7FirewallRules to the update network appliance firewall l7 firewall rules params
func (o *UpdateNetworkApplianceFirewallL7FirewallRulesParams) WithUpdateNetworkApplianceFirewallL7FirewallRules(updateNetworkApplianceFirewallL7FirewallRules UpdateNetworkApplianceFirewallL7FirewallRulesBody) *UpdateNetworkApplianceFirewallL7FirewallRulesParams {
	o.SetUpdateNetworkApplianceFirewallL7FirewallRules(updateNetworkApplianceFirewallL7FirewallRules)
	return o
}

// SetUpdateNetworkApplianceFirewallL7FirewallRules adds the updateNetworkApplianceFirewallL7FirewallRules to the update network appliance firewall l7 firewall rules params
func (o *UpdateNetworkApplianceFirewallL7FirewallRulesParams) SetUpdateNetworkApplianceFirewallL7FirewallRules(updateNetworkApplianceFirewallL7FirewallRules UpdateNetworkApplianceFirewallL7FirewallRulesBody) {
	o.UpdateNetworkApplianceFirewallL7FirewallRules = updateNetworkApplianceFirewallL7FirewallRules
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateNetworkApplianceFirewallL7FirewallRulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.UpdateNetworkApplianceFirewallL7FirewallRules); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
