// Code generated by go-swagger; DO NOT EDIT.

package appliance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateNetworkApplianceConnectivityMonitoringDestinationsParams creates a new UpdateNetworkApplianceConnectivityMonitoringDestinationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateNetworkApplianceConnectivityMonitoringDestinationsParams() *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams {
	return &UpdateNetworkApplianceConnectivityMonitoringDestinationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateNetworkApplianceConnectivityMonitoringDestinationsParamsWithTimeout creates a new UpdateNetworkApplianceConnectivityMonitoringDestinationsParams object
// with the ability to set a timeout on a request.
func NewUpdateNetworkApplianceConnectivityMonitoringDestinationsParamsWithTimeout(timeout time.Duration) *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams {
	return &UpdateNetworkApplianceConnectivityMonitoringDestinationsParams{
		timeout: timeout,
	}
}

// NewUpdateNetworkApplianceConnectivityMonitoringDestinationsParamsWithContext creates a new UpdateNetworkApplianceConnectivityMonitoringDestinationsParams object
// with the ability to set a context for a request.
func NewUpdateNetworkApplianceConnectivityMonitoringDestinationsParamsWithContext(ctx context.Context) *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams {
	return &UpdateNetworkApplianceConnectivityMonitoringDestinationsParams{
		Context: ctx,
	}
}

// NewUpdateNetworkApplianceConnectivityMonitoringDestinationsParamsWithHTTPClient creates a new UpdateNetworkApplianceConnectivityMonitoringDestinationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateNetworkApplianceConnectivityMonitoringDestinationsParamsWithHTTPClient(client *http.Client) *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams {
	return &UpdateNetworkApplianceConnectivityMonitoringDestinationsParams{
		HTTPClient: client,
	}
}

/* UpdateNetworkApplianceConnectivityMonitoringDestinationsParams contains all the parameters to send to the API endpoint
   for the update network appliance connectivity monitoring destinations operation.

   Typically these are written to a http.Request.
*/
type UpdateNetworkApplianceConnectivityMonitoringDestinationsParams struct {

	// NetworkID.
	NetworkID string

	// UpdateNetworkApplianceConnectivityMonitoringDestinations.
	UpdateNetworkApplianceConnectivityMonitoringDestinations UpdateNetworkApplianceConnectivityMonitoringDestinationsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update network appliance connectivity monitoring destinations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams) WithDefaults() *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update network appliance connectivity monitoring destinations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update network appliance connectivity monitoring destinations params
func (o *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams) WithTimeout(timeout time.Duration) *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update network appliance connectivity monitoring destinations params
func (o *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update network appliance connectivity monitoring destinations params
func (o *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams) WithContext(ctx context.Context) *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update network appliance connectivity monitoring destinations params
func (o *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update network appliance connectivity monitoring destinations params
func (o *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams) WithHTTPClient(client *http.Client) *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update network appliance connectivity monitoring destinations params
func (o *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the update network appliance connectivity monitoring destinations params
func (o *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams) WithNetworkID(networkID string) *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the update network appliance connectivity monitoring destinations params
func (o *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WithUpdateNetworkApplianceConnectivityMonitoringDestinations adds the updateNetworkApplianceConnectivityMonitoringDestinations to the update network appliance connectivity monitoring destinations params
func (o *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams) WithUpdateNetworkApplianceConnectivityMonitoringDestinations(updateNetworkApplianceConnectivityMonitoringDestinations UpdateNetworkApplianceConnectivityMonitoringDestinationsBody) *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams {
	o.SetUpdateNetworkApplianceConnectivityMonitoringDestinations(updateNetworkApplianceConnectivityMonitoringDestinations)
	return o
}

// SetUpdateNetworkApplianceConnectivityMonitoringDestinations adds the updateNetworkApplianceConnectivityMonitoringDestinations to the update network appliance connectivity monitoring destinations params
func (o *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams) SetUpdateNetworkApplianceConnectivityMonitoringDestinations(updateNetworkApplianceConnectivityMonitoringDestinations UpdateNetworkApplianceConnectivityMonitoringDestinationsBody) {
	o.UpdateNetworkApplianceConnectivityMonitoringDestinations = updateNetworkApplianceConnectivityMonitoringDestinations
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateNetworkApplianceConnectivityMonitoringDestinationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.UpdateNetworkApplianceConnectivityMonitoringDestinations); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
