// Code generated by go-swagger; DO NOT EDIT.

package switch_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDeviceSwitchPortParams creates a new GetDeviceSwitchPortParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDeviceSwitchPortParams() *GetDeviceSwitchPortParams {
	return &GetDeviceSwitchPortParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDeviceSwitchPortParamsWithTimeout creates a new GetDeviceSwitchPortParams object
// with the ability to set a timeout on a request.
func NewGetDeviceSwitchPortParamsWithTimeout(timeout time.Duration) *GetDeviceSwitchPortParams {
	return &GetDeviceSwitchPortParams{
		timeout: timeout,
	}
}

// NewGetDeviceSwitchPortParamsWithContext creates a new GetDeviceSwitchPortParams object
// with the ability to set a context for a request.
func NewGetDeviceSwitchPortParamsWithContext(ctx context.Context) *GetDeviceSwitchPortParams {
	return &GetDeviceSwitchPortParams{
		Context: ctx,
	}
}

// NewGetDeviceSwitchPortParamsWithHTTPClient creates a new GetDeviceSwitchPortParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDeviceSwitchPortParamsWithHTTPClient(client *http.Client) *GetDeviceSwitchPortParams {
	return &GetDeviceSwitchPortParams{
		HTTPClient: client,
	}
}

/* GetDeviceSwitchPortParams contains all the parameters to send to the API endpoint
   for the get device switch port operation.

   Typically these are written to a http.Request.
*/
type GetDeviceSwitchPortParams struct {

	// PortID.
	PortID string

	// Serial.
	Serial string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get device switch port params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDeviceSwitchPortParams) WithDefaults() *GetDeviceSwitchPortParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get device switch port params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDeviceSwitchPortParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get device switch port params
func (o *GetDeviceSwitchPortParams) WithTimeout(timeout time.Duration) *GetDeviceSwitchPortParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get device switch port params
func (o *GetDeviceSwitchPortParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get device switch port params
func (o *GetDeviceSwitchPortParams) WithContext(ctx context.Context) *GetDeviceSwitchPortParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get device switch port params
func (o *GetDeviceSwitchPortParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get device switch port params
func (o *GetDeviceSwitchPortParams) WithHTTPClient(client *http.Client) *GetDeviceSwitchPortParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get device switch port params
func (o *GetDeviceSwitchPortParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPortID adds the portID to the get device switch port params
func (o *GetDeviceSwitchPortParams) WithPortID(portID string) *GetDeviceSwitchPortParams {
	o.SetPortID(portID)
	return o
}

// SetPortID adds the portId to the get device switch port params
func (o *GetDeviceSwitchPortParams) SetPortID(portID string) {
	o.PortID = portID
}

// WithSerial adds the serial to the get device switch port params
func (o *GetDeviceSwitchPortParams) WithSerial(serial string) *GetDeviceSwitchPortParams {
	o.SetSerial(serial)
	return o
}

// SetSerial adds the serial to the get device switch port params
func (o *GetDeviceSwitchPortParams) SetSerial(serial string) {
	o.Serial = serial
}

// WriteToRequest writes these params to a swagger request
func (o *GetDeviceSwitchPortParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param portId
	if err := r.SetPathParam("portId", o.PortID); err != nil {
		return err
	}

	// path param serial
	if err := r.SetPathParam("serial", o.Serial); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
