// Code generated by go-swagger; DO NOT EDIT.

package switch_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNetworkSwitchRoutingMulticastParams creates a new GetNetworkSwitchRoutingMulticastParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNetworkSwitchRoutingMulticastParams() *GetNetworkSwitchRoutingMulticastParams {
	return &GetNetworkSwitchRoutingMulticastParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNetworkSwitchRoutingMulticastParamsWithTimeout creates a new GetNetworkSwitchRoutingMulticastParams object
// with the ability to set a timeout on a request.
func NewGetNetworkSwitchRoutingMulticastParamsWithTimeout(timeout time.Duration) *GetNetworkSwitchRoutingMulticastParams {
	return &GetNetworkSwitchRoutingMulticastParams{
		timeout: timeout,
	}
}

// NewGetNetworkSwitchRoutingMulticastParamsWithContext creates a new GetNetworkSwitchRoutingMulticastParams object
// with the ability to set a context for a request.
func NewGetNetworkSwitchRoutingMulticastParamsWithContext(ctx context.Context) *GetNetworkSwitchRoutingMulticastParams {
	return &GetNetworkSwitchRoutingMulticastParams{
		Context: ctx,
	}
}

// NewGetNetworkSwitchRoutingMulticastParamsWithHTTPClient creates a new GetNetworkSwitchRoutingMulticastParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNetworkSwitchRoutingMulticastParamsWithHTTPClient(client *http.Client) *GetNetworkSwitchRoutingMulticastParams {
	return &GetNetworkSwitchRoutingMulticastParams{
		HTTPClient: client,
	}
}

/* GetNetworkSwitchRoutingMulticastParams contains all the parameters to send to the API endpoint
   for the get network switch routing multicast operation.

   Typically these are written to a http.Request.
*/
type GetNetworkSwitchRoutingMulticastParams struct {

	// NetworkID.
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get network switch routing multicast params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkSwitchRoutingMulticastParams) WithDefaults() *GetNetworkSwitchRoutingMulticastParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get network switch routing multicast params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkSwitchRoutingMulticastParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get network switch routing multicast params
func (o *GetNetworkSwitchRoutingMulticastParams) WithTimeout(timeout time.Duration) *GetNetworkSwitchRoutingMulticastParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get network switch routing multicast params
func (o *GetNetworkSwitchRoutingMulticastParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get network switch routing multicast params
func (o *GetNetworkSwitchRoutingMulticastParams) WithContext(ctx context.Context) *GetNetworkSwitchRoutingMulticastParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get network switch routing multicast params
func (o *GetNetworkSwitchRoutingMulticastParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get network switch routing multicast params
func (o *GetNetworkSwitchRoutingMulticastParams) WithHTTPClient(client *http.Client) *GetNetworkSwitchRoutingMulticastParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get network switch routing multicast params
func (o *GetNetworkSwitchRoutingMulticastParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the get network switch routing multicast params
func (o *GetNetworkSwitchRoutingMulticastParams) WithNetworkID(networkID string) *GetNetworkSwitchRoutingMulticastParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the get network switch routing multicast params
func (o *GetNetworkSwitchRoutingMulticastParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNetworkSwitchRoutingMulticastParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
