// Code generated by go-swagger; DO NOT EDIT.

package sm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOrganizationSmVppAccountParams creates a new GetOrganizationSmVppAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrganizationSmVppAccountParams() *GetOrganizationSmVppAccountParams {
	return &GetOrganizationSmVppAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationSmVppAccountParamsWithTimeout creates a new GetOrganizationSmVppAccountParams object
// with the ability to set a timeout on a request.
func NewGetOrganizationSmVppAccountParamsWithTimeout(timeout time.Duration) *GetOrganizationSmVppAccountParams {
	return &GetOrganizationSmVppAccountParams{
		timeout: timeout,
	}
}

// NewGetOrganizationSmVppAccountParamsWithContext creates a new GetOrganizationSmVppAccountParams object
// with the ability to set a context for a request.
func NewGetOrganizationSmVppAccountParamsWithContext(ctx context.Context) *GetOrganizationSmVppAccountParams {
	return &GetOrganizationSmVppAccountParams{
		Context: ctx,
	}
}

// NewGetOrganizationSmVppAccountParamsWithHTTPClient creates a new GetOrganizationSmVppAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrganizationSmVppAccountParamsWithHTTPClient(client *http.Client) *GetOrganizationSmVppAccountParams {
	return &GetOrganizationSmVppAccountParams{
		HTTPClient: client,
	}
}

/* GetOrganizationSmVppAccountParams contains all the parameters to send to the API endpoint
   for the get organization sm vpp account operation.

   Typically these are written to a http.Request.
*/
type GetOrganizationSmVppAccountParams struct {

	// OrganizationID.
	OrganizationID string

	// VppAccountID.
	VppAccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get organization sm vpp account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationSmVppAccountParams) WithDefaults() *GetOrganizationSmVppAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get organization sm vpp account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationSmVppAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get organization sm vpp account params
func (o *GetOrganizationSmVppAccountParams) WithTimeout(timeout time.Duration) *GetOrganizationSmVppAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization sm vpp account params
func (o *GetOrganizationSmVppAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization sm vpp account params
func (o *GetOrganizationSmVppAccountParams) WithContext(ctx context.Context) *GetOrganizationSmVppAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization sm vpp account params
func (o *GetOrganizationSmVppAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization sm vpp account params
func (o *GetOrganizationSmVppAccountParams) WithHTTPClient(client *http.Client) *GetOrganizationSmVppAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization sm vpp account params
func (o *GetOrganizationSmVppAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the get organization sm vpp account params
func (o *GetOrganizationSmVppAccountParams) WithOrganizationID(organizationID string) *GetOrganizationSmVppAccountParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get organization sm vpp account params
func (o *GetOrganizationSmVppAccountParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithVppAccountID adds the vppAccountID to the get organization sm vpp account params
func (o *GetOrganizationSmVppAccountParams) WithVppAccountID(vppAccountID string) *GetOrganizationSmVppAccountParams {
	o.SetVppAccountID(vppAccountID)
	return o
}

// SetVppAccountID adds the vppAccountId to the get organization sm vpp account params
func (o *GetOrganizationSmVppAccountParams) SetVppAccountID(vppAccountID string) {
	o.VppAccountID = vppAccountID
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationSmVppAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	// path param vppAccountId
	if err := r.SetPathParam("vppAccountId", o.VppAccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
