// Code generated by go-swagger; DO NOT EDIT.

package cellular_gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateNetworkCellularGatewaySubnetPoolReader is a Reader for the UpdateNetworkCellularGatewaySubnetPool structure.
type UpdateNetworkCellularGatewaySubnetPoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateNetworkCellularGatewaySubnetPoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateNetworkCellularGatewaySubnetPoolOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateNetworkCellularGatewaySubnetPoolOK creates a UpdateNetworkCellularGatewaySubnetPoolOK with default headers values
func NewUpdateNetworkCellularGatewaySubnetPoolOK() *UpdateNetworkCellularGatewaySubnetPoolOK {
	return &UpdateNetworkCellularGatewaySubnetPoolOK{}
}

/* UpdateNetworkCellularGatewaySubnetPoolOK describes a response with status code 200, with default header values.

Successful operation
*/
type UpdateNetworkCellularGatewaySubnetPoolOK struct {
	Payload interface{}
}

func (o *UpdateNetworkCellularGatewaySubnetPoolOK) Error() string {
	return fmt.Sprintf("[PUT /networks/{networkId}/cellularGateway/subnetPool][%d] updateNetworkCellularGatewaySubnetPoolOK  %+v", 200, o.Payload)
}
func (o *UpdateNetworkCellularGatewaySubnetPoolOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UpdateNetworkCellularGatewaySubnetPoolOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*UpdateNetworkCellularGatewaySubnetPoolBody update network cellular gateway subnet pool body
// Example: {"cidr":"192.168.0.0/16","deploymentMode":"routed","mask":24}
swagger:model UpdateNetworkCellularGatewaySubnetPoolBody
*/
type UpdateNetworkCellularGatewaySubnetPoolBody struct {

	// CIDR of the pool of subnets. Each MG in this network will automatically pick a subnet from this pool.
	Cidr string `json:"cidr,omitempty"`

	// Mask used for the subnet of all MGs in  this network.
	Mask int64 `json:"mask,omitempty"`
}

// Validate validates this update network cellular gateway subnet pool body
func (o *UpdateNetworkCellularGatewaySubnetPoolBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update network cellular gateway subnet pool body based on context it is used
func (o *UpdateNetworkCellularGatewaySubnetPoolBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateNetworkCellularGatewaySubnetPoolBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateNetworkCellularGatewaySubnetPoolBody) UnmarshalBinary(b []byte) error {
	var res UpdateNetworkCellularGatewaySubnetPoolBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
