// Code generated by go-swagger; DO NOT EDIT.

package wireless

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNetworkWirelessBillingParams creates a new GetNetworkWirelessBillingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNetworkWirelessBillingParams() *GetNetworkWirelessBillingParams {
	return &GetNetworkWirelessBillingParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNetworkWirelessBillingParamsWithTimeout creates a new GetNetworkWirelessBillingParams object
// with the ability to set a timeout on a request.
func NewGetNetworkWirelessBillingParamsWithTimeout(timeout time.Duration) *GetNetworkWirelessBillingParams {
	return &GetNetworkWirelessBillingParams{
		timeout: timeout,
	}
}

// NewGetNetworkWirelessBillingParamsWithContext creates a new GetNetworkWirelessBillingParams object
// with the ability to set a context for a request.
func NewGetNetworkWirelessBillingParamsWithContext(ctx context.Context) *GetNetworkWirelessBillingParams {
	return &GetNetworkWirelessBillingParams{
		Context: ctx,
	}
}

// NewGetNetworkWirelessBillingParamsWithHTTPClient creates a new GetNetworkWirelessBillingParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNetworkWirelessBillingParamsWithHTTPClient(client *http.Client) *GetNetworkWirelessBillingParams {
	return &GetNetworkWirelessBillingParams{
		HTTPClient: client,
	}
}

/* GetNetworkWirelessBillingParams contains all the parameters to send to the API endpoint
   for the get network wireless billing operation.

   Typically these are written to a http.Request.
*/
type GetNetworkWirelessBillingParams struct {

	// NetworkID.
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get network wireless billing params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkWirelessBillingParams) WithDefaults() *GetNetworkWirelessBillingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get network wireless billing params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkWirelessBillingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get network wireless billing params
func (o *GetNetworkWirelessBillingParams) WithTimeout(timeout time.Duration) *GetNetworkWirelessBillingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get network wireless billing params
func (o *GetNetworkWirelessBillingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get network wireless billing params
func (o *GetNetworkWirelessBillingParams) WithContext(ctx context.Context) *GetNetworkWirelessBillingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get network wireless billing params
func (o *GetNetworkWirelessBillingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get network wireless billing params
func (o *GetNetworkWirelessBillingParams) WithHTTPClient(client *http.Client) *GetNetworkWirelessBillingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get network wireless billing params
func (o *GetNetworkWirelessBillingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the get network wireless billing params
func (o *GetNetworkWirelessBillingParams) WithNetworkID(networkID string) *GetNetworkWirelessBillingParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the get network wireless billing params
func (o *GetNetworkWirelessBillingParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNetworkWirelessBillingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
