// Code generated by go-swagger; DO NOT EDIT.

package wireless

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetDeviceWirelessRadioSettingsReader is a Reader for the GetDeviceWirelessRadioSettings structure.
type GetDeviceWirelessRadioSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeviceWirelessRadioSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeviceWirelessRadioSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDeviceWirelessRadioSettingsOK creates a GetDeviceWirelessRadioSettingsOK with default headers values
func NewGetDeviceWirelessRadioSettingsOK() *GetDeviceWirelessRadioSettingsOK {
	return &GetDeviceWirelessRadioSettingsOK{}
}

/* GetDeviceWirelessRadioSettingsOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetDeviceWirelessRadioSettingsOK struct {
	Payload interface{}
}

func (o *GetDeviceWirelessRadioSettingsOK) Error() string {
	return fmt.Sprintf("[GET /devices/{serial}/wireless/radio/settings][%d] getDeviceWirelessRadioSettingsOK  %+v", 200, o.Payload)
}
func (o *GetDeviceWirelessRadioSettingsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetDeviceWirelessRadioSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
