// Code generated by go-swagger; DO NOT EDIT.

package wireless

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDeviceWirelessRadioSettingsParams creates a new GetDeviceWirelessRadioSettingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDeviceWirelessRadioSettingsParams() *GetDeviceWirelessRadioSettingsParams {
	return &GetDeviceWirelessRadioSettingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDeviceWirelessRadioSettingsParamsWithTimeout creates a new GetDeviceWirelessRadioSettingsParams object
// with the ability to set a timeout on a request.
func NewGetDeviceWirelessRadioSettingsParamsWithTimeout(timeout time.Duration) *GetDeviceWirelessRadioSettingsParams {
	return &GetDeviceWirelessRadioSettingsParams{
		timeout: timeout,
	}
}

// NewGetDeviceWirelessRadioSettingsParamsWithContext creates a new GetDeviceWirelessRadioSettingsParams object
// with the ability to set a context for a request.
func NewGetDeviceWirelessRadioSettingsParamsWithContext(ctx context.Context) *GetDeviceWirelessRadioSettingsParams {
	return &GetDeviceWirelessRadioSettingsParams{
		Context: ctx,
	}
}

// NewGetDeviceWirelessRadioSettingsParamsWithHTTPClient creates a new GetDeviceWirelessRadioSettingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDeviceWirelessRadioSettingsParamsWithHTTPClient(client *http.Client) *GetDeviceWirelessRadioSettingsParams {
	return &GetDeviceWirelessRadioSettingsParams{
		HTTPClient: client,
	}
}

/* GetDeviceWirelessRadioSettingsParams contains all the parameters to send to the API endpoint
   for the get device wireless radio settings operation.

   Typically these are written to a http.Request.
*/
type GetDeviceWirelessRadioSettingsParams struct {

	// Serial.
	Serial string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get device wireless radio settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDeviceWirelessRadioSettingsParams) WithDefaults() *GetDeviceWirelessRadioSettingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get device wireless radio settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDeviceWirelessRadioSettingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get device wireless radio settings params
func (o *GetDeviceWirelessRadioSettingsParams) WithTimeout(timeout time.Duration) *GetDeviceWirelessRadioSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get device wireless radio settings params
func (o *GetDeviceWirelessRadioSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get device wireless radio settings params
func (o *GetDeviceWirelessRadioSettingsParams) WithContext(ctx context.Context) *GetDeviceWirelessRadioSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get device wireless radio settings params
func (o *GetDeviceWirelessRadioSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get device wireless radio settings params
func (o *GetDeviceWirelessRadioSettingsParams) WithHTTPClient(client *http.Client) *GetDeviceWirelessRadioSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get device wireless radio settings params
func (o *GetDeviceWirelessRadioSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSerial adds the serial to the get device wireless radio settings params
func (o *GetDeviceWirelessRadioSettingsParams) WithSerial(serial string) *GetDeviceWirelessRadioSettingsParams {
	o.SetSerial(serial)
	return o
}

// SetSerial adds the serial to the get device wireless radio settings params
func (o *GetDeviceWirelessRadioSettingsParams) SetSerial(serial string) {
	o.Serial = serial
}

// WriteToRequest writes these params to a swagger request
func (o *GetDeviceWirelessRadioSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param serial
	if err := r.SetPathParam("serial", o.Serial); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
