// Code generated by go-swagger; DO NOT EDIT.

package wireless

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateNetworkWirelessAlternateManagementInterfaceParams creates a new UpdateNetworkWirelessAlternateManagementInterfaceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateNetworkWirelessAlternateManagementInterfaceParams() *UpdateNetworkWirelessAlternateManagementInterfaceParams {
	return &UpdateNetworkWirelessAlternateManagementInterfaceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateNetworkWirelessAlternateManagementInterfaceParamsWithTimeout creates a new UpdateNetworkWirelessAlternateManagementInterfaceParams object
// with the ability to set a timeout on a request.
func NewUpdateNetworkWirelessAlternateManagementInterfaceParamsWithTimeout(timeout time.Duration) *UpdateNetworkWirelessAlternateManagementInterfaceParams {
	return &UpdateNetworkWirelessAlternateManagementInterfaceParams{
		timeout: timeout,
	}
}

// NewUpdateNetworkWirelessAlternateManagementInterfaceParamsWithContext creates a new UpdateNetworkWirelessAlternateManagementInterfaceParams object
// with the ability to set a context for a request.
func NewUpdateNetworkWirelessAlternateManagementInterfaceParamsWithContext(ctx context.Context) *UpdateNetworkWirelessAlternateManagementInterfaceParams {
	return &UpdateNetworkWirelessAlternateManagementInterfaceParams{
		Context: ctx,
	}
}

// NewUpdateNetworkWirelessAlternateManagementInterfaceParamsWithHTTPClient creates a new UpdateNetworkWirelessAlternateManagementInterfaceParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateNetworkWirelessAlternateManagementInterfaceParamsWithHTTPClient(client *http.Client) *UpdateNetworkWirelessAlternateManagementInterfaceParams {
	return &UpdateNetworkWirelessAlternateManagementInterfaceParams{
		HTTPClient: client,
	}
}

/* UpdateNetworkWirelessAlternateManagementInterfaceParams contains all the parameters to send to the API endpoint
   for the update network wireless alternate management interface operation.

   Typically these are written to a http.Request.
*/
type UpdateNetworkWirelessAlternateManagementInterfaceParams struct {

	// NetworkID.
	NetworkID string

	// UpdateNetworkWirelessAlternateManagementInterface.
	UpdateNetworkWirelessAlternateManagementInterface UpdateNetworkWirelessAlternateManagementInterfaceBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update network wireless alternate management interface params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateNetworkWirelessAlternateManagementInterfaceParams) WithDefaults() *UpdateNetworkWirelessAlternateManagementInterfaceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update network wireless alternate management interface params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateNetworkWirelessAlternateManagementInterfaceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update network wireless alternate management interface params
func (o *UpdateNetworkWirelessAlternateManagementInterfaceParams) WithTimeout(timeout time.Duration) *UpdateNetworkWirelessAlternateManagementInterfaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update network wireless alternate management interface params
func (o *UpdateNetworkWirelessAlternateManagementInterfaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update network wireless alternate management interface params
func (o *UpdateNetworkWirelessAlternateManagementInterfaceParams) WithContext(ctx context.Context) *UpdateNetworkWirelessAlternateManagementInterfaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update network wireless alternate management interface params
func (o *UpdateNetworkWirelessAlternateManagementInterfaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update network wireless alternate management interface params
func (o *UpdateNetworkWirelessAlternateManagementInterfaceParams) WithHTTPClient(client *http.Client) *UpdateNetworkWirelessAlternateManagementInterfaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update network wireless alternate management interface params
func (o *UpdateNetworkWirelessAlternateManagementInterfaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the update network wireless alternate management interface params
func (o *UpdateNetworkWirelessAlternateManagementInterfaceParams) WithNetworkID(networkID string) *UpdateNetworkWirelessAlternateManagementInterfaceParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the update network wireless alternate management interface params
func (o *UpdateNetworkWirelessAlternateManagementInterfaceParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WithUpdateNetworkWirelessAlternateManagementInterface adds the updateNetworkWirelessAlternateManagementInterface to the update network wireless alternate management interface params
func (o *UpdateNetworkWirelessAlternateManagementInterfaceParams) WithUpdateNetworkWirelessAlternateManagementInterface(updateNetworkWirelessAlternateManagementInterface UpdateNetworkWirelessAlternateManagementInterfaceBody) *UpdateNetworkWirelessAlternateManagementInterfaceParams {
	o.SetUpdateNetworkWirelessAlternateManagementInterface(updateNetworkWirelessAlternateManagementInterface)
	return o
}

// SetUpdateNetworkWirelessAlternateManagementInterface adds the updateNetworkWirelessAlternateManagementInterface to the update network wireless alternate management interface params
func (o *UpdateNetworkWirelessAlternateManagementInterfaceParams) SetUpdateNetworkWirelessAlternateManagementInterface(updateNetworkWirelessAlternateManagementInterface UpdateNetworkWirelessAlternateManagementInterfaceBody) {
	o.UpdateNetworkWirelessAlternateManagementInterface = updateNetworkWirelessAlternateManagementInterface
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateNetworkWirelessAlternateManagementInterfaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.UpdateNetworkWirelessAlternateManagementInterface); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
